//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicantSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ZipCode { get; set; }
        public string Phone { get; set; }
        public string SalaryRequired { get; set; }
        public string Level_of_Expertise { get; set; }
        public int YearsOfExperience { get; set; }
        public string EducationLevel { get; set; }
        public Nullable<bool> GoodRecruit { get; set; }
    }
}
